upgrade: false
interactive: false
verbose: false
# Remove version ranges from the final package version.
removeRange: true
# Not update peerDependencies version.
peer: false

# Modify the output formatting or show additional
# information. Specify one or more comma-delimited
# choices: group, ownerChanged, repo.
format: group

# Determines the version to upgrade to.
# choices: latest, newest, greatest, minor, patch
target: latest

# Include only package names matching the given string, wildcard, glob,
# comma-or-space-delimited list, or /regex/
filter:
  - "*"

# Exclude packages matching the given string, wildcard, glob,
# comma-or-space-delimited list, or /regex/
reject:
  # Jest environment will upgrade based on heft-jest-plugin
  - "jest-environment-jsdom"
  - "jest-environment-node"
  # This depends on Heft to upgrade
  - "typescript"
  # This should be pin to oldest version we supported
  - "@types/node"
