shared:
  pr-status: &pr_status
    - -closed
    - -draft
    - -conflict
    - "#review-threads-unresolved=0"
  ci-status: &ci_status
    - check-success=changelog
    - check-success=linting
    - check-success=testing

queue_rules:
  - name: default
    conditions:
      - and: *pr_status
      - and: *ci_status

pull_request_rules:
  - name: Convert wip to draft PR
    conditions:
      - label=wip
    actions:
      edit:
        draft: True
      label:
        remove:
          - wip
  - name: Automatic merging by approval
    conditions:
      - "#approved-reviews-by>=1"
    actions:
      queue:
        name: default
  - name: Automatic merging by owner
    conditions:
      - or:
        - author=kc-bot
        - author=kamontat
      - base=main
    actions:
      queue:
        name: default
  - name: Notify author on queue failure
    conditions:
      - 'check-failure=Queue: Embarked in merge train'
    actions:
      comment:
        message: >
          Hey @{{ author }}, this pull request failed to merge and has been
          dequeued from the merge train. If you believe your PR failed in
          the merge train because of a flaky test, requeue it by commenting
          with `@mergifyio requeue`.
          More details can be found on the `Queue: Embarked in merge train`
          check-run.
