shared:
  pr-status: &pr_status
    - -closed
    - -draft
    - -conflict
    - "#review-threads-unresolved=0"
  ci-status: &ci_status
    - check-success=changelog
    - check-success=linting
    - check-success=testing

queue_rules:
  - name: default
    conditions:
      - and: *pr_status
      - and: *ci_status

pull_request_rules:
  - name: Convert wip to draft PR
    conditions:
      - label=wip
    actions:
      edit:
        draft: True
      label:
        remove:
          - wip
  - name: Automatic merging by approval
    conditions:
      - "#approved-reviews-by>=1"
    actions:
      queue:
        name: default
  - name: Automatic merging by owner
    conditions:
      - or:
        - author=kc-bot
        - author=kamontat
      - base=main
    actions:
      queue:
        name: default
