shared:
  pr-status: &pr_status
    - -closed
    - -draft
    - -conflict
    - -label=do-not-automerge
    - "#review-threads-unresolved=0"
  ci-status: &ci_status
    - check-success=changelog
    - check-success=lintcheck
    - check-success=spellcheck
    - check-success=licensecheck
    - check-success=testing
    - check-success=alternative-testing (18)
    - check-success=alternative-testing (20)

queue_rules:
  - name: duplicated default from Automatic merging by owner
    queue_conditions:
      - "#approved-reviews-by>=1"
      - or:
          - author=kc-bot
          - author=kamontat
      - base=main
    merge_conditions: []
    merge_method: squash
    method: squash
  - name: default
    queue_conditions:
      - "#approved-reviews-by>=1"
    merge_conditions:
      - and: *pr_status
      - and: *ci_status

    merge_method: squash

pull_request_rules:
  - name: Convert wip to draft PR
    conditions:
      - label=wip
    actions:
      edit:
        draft: true
      label:
        remove:
          - wip
  - name: Notify author on queue failure
    conditions:
      - "check-failure=Queue: Embarked in merge train"
    actions:
      comment:
        message: >
          Hey @{{ author }}, this pull request failed to merge and has been
          dequeued from the merge train. If you believe your PR failed in
          the merge train because of a flaky test, requeue it by commenting
          with `@mergifyio requeue`.
          More details can be found on the `Queue: Embarked in merge train`
          check-run.
  - name: refactored queue action rule
    conditions: []
    actions:
      queue:
