upgrade: false
interactive: false
verbose: false
# Remove version ranges from the final package version.
removeRange: true
format: group
# Include only package names matching the given string, wildcard, glob,
# comma-or-space-delimited list, or /regex/
filter:
  - "*"

# Exclude packages matching the given string, wildcard, glob,
# comma-or-space-delimited list, or /regex/
reject:
  - "@types/*"

doctorInstall: rush install
doctorTest: rush test
