upgrade: false
interactive: false
verbose: false
# Remove version ranges from the final package version.
removeRange: true

# Modify the output formatting or show additional
# information. Specify one or more comma-delimited
# choices: group, ownerChanged, repo.
format: group

# Determines the version to upgrade to.
# choices: latest, newest, greatest, minor, patch
target: minor

# Include only package names matching the given string, wildcard, glob,
# comma-or-space-delimited list, or /regex/
filter:
  - "*"

# Exclude packages matching the given string, wildcard, glob,
# comma-or-space-delimited list, or /regex/
reject:
  - "@types/*"
