name: Setup git
description: setup git and github cli
author: Kamontat Chantrachirathumrong

runs:
  using: composite
  steps:
    - name: Show information
      run: $GITHUB_ACTION_PATH/show-information.sh
      shell: bash
    - name: Setup git config
      run: $GITHUB_ACTION_PATH/setup-git.sh
      shell: bash
    - name: Setup gpg
      run: $GITHUB_ACTION_PATH/setup-gpg.sh
      shell: bash
