#!/bin/sh

act_format="hooks:format"
act_docs="hooks:docs"

if command -v "rush" >/dev/null 2>&1; then
  rush "$act_format" || exit $?
  rush "$act_docs" || exit $?
else
  node common/scripts/install-run-rush.js "$act_format" || exit $?
  node common/scripts/install-run-rush.js "$act_docs" || exit $?
fi

unset act_format act_docs
