#!/bin/sh

act_format="hooks:format"

if command -v "rush" >/dev/null 2>&1; then
  rush "$act_format" || exit $?
else
  node common/scripts/install-run-rush.js "$act_format" || exit $?
fi

unset act_format
