#!/bin/sh

action="change"
arg="-v"

if command -v "rush" >/dev/null 2>&1; then
  rush "$action" "$arg" || exit $?
else
  node common/scripts/install-run-rush.js "$action" "$arg" || exit $?
fi

unset action arg
