#!/bin/sh

## Do NOT run on CI machine
if test -n "$CI"; then
  exit 0
fi

action="change"
arg="-v"

if command -v "rush" >/dev/null 2>&1; then
  rush "$action" "$arg" || exit 1
else
  node common/scripts/install-run-rush.js "$action" "$arg" || exit 1
fi

unset action arg
