name: Setup rush
description: Setup rush using install-run-rush.js script
author: Kamontat Chantrachirathumrong
inputs:
  node-version:
    description: Install nodejs version
    default: ""
  install:
    description: Install dependencies after setup rush repository
    default: "true"
  install-cache:
    description: Enabled caching installed dependencies
    default: "true"
  build:
    description: Build applications after setup rush repository
    default: "false"
  build-cache:
    description: Enabled caching built applications
    default: "false"
  rush-cache:
    description: Enabled caching installed rush
    default: "true"

runs:
  using: composite
  steps:
    - name: Setup NodeJS
      id: nodejs
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        node-version-file: .tool-versions

    - name: Caching rush
      if: inputs.rush-cache == 'true'
      uses: actions/cache@v4
      with:
        path: common/temp/install-run
        key: rush-${{ runner.os }}-${{ steps.nodejs.outputs.node-version }}-${{ hashFiles('rush.json') }}
        restore-keys: |
          rush-${{ runner.os }}-${{ steps.nodejs.outputs.node-version }}-
          rush-${{ runner.os }}-
          rush-
    - name: Installing rush
      ## Run any command from install-run-rush.sh script to download rush if not existed
      run: node common/scripts/install-run-rush.js --help >/dev/null
      shell: bash

    - name: Caching pnpm packages
      if: inputs.install-cache == 'true' && inputs.install == 'true'
      uses: actions/cache@v4
      with:
        path: common/temp/pnpm-store
        key: pnpm-${{ runner.os }}-${{ steps.nodejs.outputs.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          pnpm-${{ runner.os }}-${{ steps.nodejs.outputs.node-version }}-
          pnpm-${{ runner.os }}-
          pnpm-
    - name: Installing pnpm packages
      if: inputs.install == 'true'
      run: node common/scripts/install-run-rush.js install
      shell: bash

    - name: Caching applications
      if: inputs.build-cache == 'true' && inputs.build == 'true'
      uses: actions/cache@v4
      with:
        path: common/temp/build-cache
        key: rush-build-${{ runner.os }}-${{ steps.nodejs.outputs.node-version }}-${{ github.run_id }}
        restore-keys: |
          rush-build-${{ runner.os }}-${{ steps.nodejs.outputs.node-version }}-
          rush-build-${{ runner.os }}-
          rush-build-
    - name: Building applications
      if: inputs.build == 'true'
      run: node common/scripts/install-run-rush.js build --timeline
      shell: bash
