name: Setup rush
description: Setup rush using install-run-rush.js script
author: Kamontat Chantrachirathumrong
inputs:
  node-version:
    description: Install nodejs version
    default: "lts/*"
  install:
    description: Install dependencies after setup rush repository
    default: "true"
  cache-rush:
    description: Enabled caching installed rush
    default: "true"
  cache-pnpm:
    description: Enabled caching pnpm store
    default: "true"
  cache-build:
    description: Enabled caching build-cache
    default: "true"

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
    - name: Caching rush
      if: inputs.cache-rush == 'true'
      uses: actions/cache@v4
      with:
        path: common/temp/install-run
        key: ${{ runner.os }}-rush-${{ hashFiles('rush.json') }}
        restore-keys: |
          ${{ runner.os }}-rush-
    - name: Caching pnpm store
      if: inputs.cache-pnpm == 'true'
      uses: actions/cache@v4
      with:
        path: common/temp/pnpm-store
        key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-
    - name: Caching build-cache
      if: inputs.cache-build == 'true'
      uses: actions/cache@v4
      with:
        path: common/temp/build-cache
        key: ${{ runner.os }}-build
        restore-keys: |
          ${{ runner.os }}-build
    - name: Installing dependencies
      if: inputs.install == 'true'
      run: node common/scripts/install-run-rush.js install
      shell: bash
