name: Typescript Example
description: Example actions written on Typescript
author: Kamontat Chantrachirathumrong

inputs:
  name:
    description: example name
  dryrun:
    description: dry-run the command instead executes
    required: false

# outputs:
#   output:
#     description: Output description

runs:
  using: node20
  main: index.js

  # NOTES: pre and post are optional, you can remove it.
  # Don't forget to remove those files from ./src directory as well
  pre: pre.js
  post: post.js
