# https://jekyllrb.com/docs/configuration/default/

title: kcws apis (js)
description: kc-workspace api documentation for javascript language

# Location
plugins_dir         : _plugins
layouts_dir         : _layouts
data_dir            : _data
includes_dir        : _includes

# Conversion
markdown            : kramdown
highlighter         : rouge
lsi                 : false
excerpt_separator   : "\n\n"
incremental         : false

# https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll
theme: cayman

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
