name: Deploy documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: gh-pages
  cancel-in-progress: true

jobs:
  building:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup rushjs
        uses: ./.github/actions/setup-rush
        with:
          install: true
      - name: Building packages
        uses: ./.github/actions/run-rush
        with:
          command: rebuild
      - name: Building documentation
        uses: ./.github/actions/run-rush
        with:
          command: docs
      - name: Building Jekyll output
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs
          destination: ./_site
      - name: Upload built document
        uses: actions/upload-pages-artifact@v1

  deploying:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs:
      - building
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
