name: Deploy packages

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  contents: read

concurrency:
  group: deployment
  cancel-in-progress: true

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup rushjs
        uses: ./.github/actions/setup-rush
        with:
          install: true
      - name: Checking for missing change logs
        uses: ./.github/actions/run-rush
        with:
          command: change
          args: --verify
      - name: Deployment summary
        uses: ./.github/actions/run-rush
        with:
          command: publish

  deploy:
    # This is to ensure main branch cannot be run
    # as well as the workflow still return passed
    #
    # I have another protected layers on environment level
    # however, that will cause deployment workflow to be failed
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: npm-registry
      url: https://www.npmjs.com/org/kcws
    needs:
      - verify
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup git
        uses: ./.github/actions/setup-git
        with:
          git-email: ${{ secrets.GIT_EMAIL }}
          git-username: ${{ secrets.GIT_USERNAME }}
          github-token: ${{ secrets.GH_TOKEN }}
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY_BASE64 }}
          gpg-fingerprint: ${{ secrets.GPG_FINGERPRINT }}
      - name: Setup rushjs
        uses: ./.github/actions/setup-rush
        with:
          install: true
      - name: Building packages
        uses: ./.github/actions/run-rush
        with:
          command: build
      - name: Deploying packages
        uses: ./.github/actions/run-rush
        with:
          command: publish
          args: >
            --apply \
            --target-branch main \
            --publish \
            --add-commit-details
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Cleanup git
        if: always()
        uses: ./.github/actions/cleanup-git
        with:
          gpg-fingerprint: ${{ secrets.GPG_FINGERPRINT }}
