name: Lint shell scripts

on:
  push:
    paths:
      - "**/*.sh"

defaults:
  run:
    shell: bash

concurrency:
  group: lint-shell-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Linting shell scripts
        run: shellcheck **/*.sh
