name: Main

on:
  push:

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DEFAULT_BRANCH: main

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup rushjs
        uses: ./.github/actions/setup-rush
        with:
          install: true
      - name: Checking for missing changelogs
        uses: ./.github/actions/run-rush
        with:
          command: change
          args: --verify

  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Running cspell
        uses: streetsidesoftware/cspell-action@v2
        with:
          config: '.github/linters'
          verbose: true
          incremental_files_only: true

  licensecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Scanning dependencies
        uses: fossas/fossa-action@v1
        with:
          api-key: ${{ secrets.FOSSA_APIKEY }}
      - name: Testing dependencies
        uses: fossas/fossa-action@v1
        with:
          api-key: ${{ secrets.FOSSA_APIKEY }}
          run-tests: true

  lintcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Linting
        # https://github.com/github/super-linter#slim-image
        uses: github/super-linter/slim@v4
        env:
          DEFAULT_BRANCH: ${{ env.DEFAULT_BRANCH }}
          VALIDATE_ALL_CODEBASE: false
          IGNORE_GITIGNORED_FILES: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          YAML_CONFIG_FILE: .yamllint.yml
          YAML_ERROR_ON_WARNING: true
          # Disabled javascript/typescript as we have lint on rushjs
          VALIDATE_JAVASCRIPT_ES: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_JSX: false
          VALIDATE_TYPESCRIPT_ES: false
          VALIDATE_TYPESCRIPT_STANDARD: false
          VALIDATE_TSX: false
          # Disabled json validation as issue #30
          VALIDATE_JSON: false

  testing:
    runs-on: ubuntu-latest
    needs:
      - changelog
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup rushjs
        uses: ./.github/actions/setup-rush
        with:
          install: true
      - name: Building packages
        uses: ./.github/actions/run-rush
        with:
          command: build
          args: --verbose
      - name: Testing packages
        uses: ./.github/actions/run-rush
        with:
          command: test
          args: --verbose
      - name: Analysis packages
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
