name: Main

on:
  push:

defaults:
  run:
    shell: bash

env:
  NODE_VERSION: 16
  PNPM_STORE_PATH: common/temp/pnpm-store/v3

concurrency:
  group: "main"
  cancel-in-progress: true

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-rush
        with:
          install: true
      - uses: ./.github/actions/run-rush
        with:
          command: change
          args: --verify

  testing:
    runs-on: ubuntu-latest
    needs:
      - changelog
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-rush
        with:
          install: true
      - uses: ./.github/actions/run-rush
        with:
          command: build
          args: --verbose
      - uses: ./.github/actions/run-rush
        with:
          command: test
          args: --verbose
