name: Main

on:
  push:

defaults:
  run:
    shell: bash

env:
  NODE_VERSION: 16
  PNPM_STORE_PATH: common/temp/pnpm-store/v3

concurrency:
  group: "main"
  cancel-in-progress: true

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Caching rush
        uses: actions/cache@v3
        with:
          path: common/temp/install-run
          key: ${{ runner.os }}-rush-${{ hashFiles('rush.json') }}
          restore-keys: |
            ${{ runner.os }}-rush-
      - name: Caching pnpm store
        uses: actions/cache@v3
        with:
          path: common/temp/pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - name: Checking for missing change logs
        run: node common/scripts/install-run-rush.js change -v

  testing:
    runs-on: ubuntu-latest
    needs:
      - changelog
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Caching rush
        uses: actions/cache@v3
        with:
          path: common/temp/install-run
          key: ${{ runner.os }}-rush-${{ hashFiles('rush.json') }}
          restore-keys: |
            ${{ runner.os }}-rush-
      - name: Caching pnpm store
        uses: actions/cache@v3
        with:
          path: common/temp/pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - name: Installing dependencies
        run: node common/scripts/install-run-rush.js install
      - name: Building applications
        run: node common/scripts/install-run-rush.js build --verbose
      - name: Testing applications
        run: node common/scripts/install-run-rush.js test --verbose
