name: Main

on:
  push:

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DEFAULT_BRANCH: main

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup rushjs
        uses: ./.github/actions/setup-rush
        with:
          install: true
          install-cache: true
          build: true
          build-cache: true
      - name: Checking for missing changelogs
        uses: ./.github/actions/run-rush
        with:
          command: change
          args: --verify
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Running cspell
        uses: streetsidesoftware/cspell-action@v5
        with:
          config: '.github/linters/cspell.json'
          # Log progress and other information during the action execution.
          verbose: true
          # Determines if the action should be failed
          # if any spelling issues are found.
          strict: true
          # Limit the files checked to the ones in the pull request or push.
          # We will enabled this only if this job tooks more than 3 minutes
          incremental_files_only: false
          # Notification level to use with inline reporting of spelling errors.
          # Allowed values are: warning, error, none
          inline: warning
  licensecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Scanning dependencies
        uses: fossas/fossa-action@main
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
      - name: Testing dependencies
        uses: fossas/fossa-action@main
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
          run-tests: true
  lintcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Linting
        ## https://github.com/super-linter/super-linter#slim-image
        uses: super-linter/super-linter/slim@v5
        env:
          DEFAULT_BRANCH: ${{ env.DEFAULT_BRANCH }}
          VALIDATE_ALL_CODEBASE: false
          IGNORE_GITIGNORED_FILES: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          YAML_CONFIG_FILE: .yamllint.yml
          YAML_ERROR_ON_WARNING: true
          # Disabled javascript/typescript as we have lint on rushjs
          VALIDATE_JAVASCRIPT_ES: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_JSX: false
          VALIDATE_TYPESCRIPT_ES: false
          VALIDATE_TYPESCRIPT_STANDARD: false
          VALIDATE_TSX: false
          # Disabled json validation as issue #30
          VALIDATE_JSON: false
          # The overrided config cannot resolve to correct path
          # so we disabled it for now.
          # For now, we only have single project using css linter
          # so we will run it manually on local.
          VALIDATE_CSS: false
          # For markdownlint, as it cannot exclude file from config file
          # exclude reviews file because it autogen file
          FILTER_REGEX_EXCLUDE: common/reviews/api/*

  testing:
    runs-on: ubuntu-latest
    needs:
      - changelog
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup rushjs
        uses: ./.github/actions/setup-rush
        with:
          install: false
          install-cache: true
          build: false
          build-cache: true
      - name: Testing packages
        uses: ./.github/actions/run-rush
        with:
          command: test
      - name: Analysis packages
        uses: SonarSource/sonarcloud-github-action@v2.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  alternative-testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Support backward 'LTS' version and 'current' version
        # https://github.com/nodejs/release#release-schedule
        # https://nodejs.org/en/blog/release
        node-version: [18, 20]
    needs:
      - testing
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Setup rushjs
        uses: ./.github/actions/setup-rush
        with:
          node-version: ${{ matrix.node-version }}
          install: true
          install-cache: true
          build: true
          build-cache: true
      - name: Testing packages
        uses: ./.github/actions/run-rush
        with:
          command: test
