name: Main

on:
  push:

defaults:
  run:
    shell: bash

concurrency:
  group: main-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup rushjs
        uses: ./.github/actions/setup-rush
        with:
          install: true
      - name: Checking for missing change logs
        uses: ./.github/actions/run-rush
        with:
          command: change
          args: --verify

  testing:
    environment:
      name: testing
      url: https://sonarcloud.io/project/overview?id=kc-workspace_kcws-js
    runs-on: ubuntu-latest
    needs:
      - changelog
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup rushjs
        uses: ./.github/actions/setup-rush
        with:
          install: true
      - name: Building packages
        uses: ./.github/actions/run-rush
        with:
          command: build
          args: --verbose
      - name: Testing packages
        uses: ./.github/actions/run-rush
        with:
          command: test
          args: --verbose
      - name: Analysis packages
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
