name: Dependencies

on:
  schedule:
    - cron: "0 3 * * 0" # https://crontab.guru/#0_3_*_*_0
  workflow_dispatch:

defaults:
  run:
    shell: bash

concurrency:
  group: "upgrade-deps"
  cancel-in-progress: true

permissions:
  pull-requests: write

env:
  CHANGE_MESSAGE: upgrade dependencies [auto]
  CHANGE_TYPE: minor

jobs:
  upgrading:
    runs-on: ubuntu-latest
    environment:
      name: github
      url: ${{ steps.create-pr.outputs.url }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Setup rushjs
        uses: ./.github/actions/setup-rush
        with:
          install: true
      - name: Setup git
        uses: ./.github/actions/setup-git
        with:
          git-email: ${{ secrets.GIT_EMAIL }}
          git-username: ${{ secrets.GIT_USERNAME }}
          github-token: ${{ secrets.GH_TOKEN }}
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY_BASE64 }}
          gpg-fingerprint: ${{ secrets.GPG_FINGERPRINT }}
      - name: Update dependencies
        uses: ./.github/actions/run-rush
        with:
          command: deps
          args: --upgrade
      - name: Upgrade dependencies
        uses: ./.github/actions/run-rush
        with:
          command: update
          args: --full --purge
      - name: Build only needed libraries for git hooks
        uses: ./.github/actions/run-rush
        with:
          command: build
          args: --to @kcws/lintstaged-config
      - name: Generate changesfile
        uses: ./.github/actions/run-rush
        with:
          command: change
          args: |
            --commit --email ${{ secrets.GIT_EMAIL }} --bulk --message ${{ env.CHANGE_MESSAGE }} --bump-type ${{ env.CHANGE_TYPE }}
      - id: create-pr
        name: Create pull request
        uses: ./.github/actions/create-pr
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          title: Upgrade dependencies
          branch-prefix: deps
          commit: true
          commit-message: "chore(deps): upgrade all dependencies"
      - name: Cleanup git
        if: always()
        uses: ./.github/actions/cleanup-git
        with:
          gpg-fingerprint: ${{ secrets.GPG_FINGERPRINT }}
