name: Upgrade dependencies

on:
  schedule:
    - cron: "0 3 * * 0" # https://crontab.guru/#0_3_*_*_0
  workflow_dispatch:

defaults:
  run:
    shell: bash

concurrency:
  group: "upgrade-deps"
  cancel-in-progress: true

jobs:
  updating:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup rushjs
        uses: ./.github/actions/setup-rush
        with:
          install: true
      - name: Update dependencies
        uses: ./.github/actions/run-rush
        with:
          command: deps
          args: --upgrade
      - name: Upgrade dependencies
        uses: ./.github/actions/run-rush
        with:
          command: update
          args: --full --purge
      - name: Checking result (via git)
        run: git status --short --branch --porcelain=v1
