name: Dependencies

on:
  schedule:
    - cron: "0 3 * * 0" # https://crontab.guru/#0_3_*_*_0
  workflow_dispatch:

defaults:
  run:
    shell: bash

concurrency:
  group: "upgrade-deps"
  cancel-in-progress: true

permissions:
  pull-requests: write

jobs:
  upgrading:
    runs-on: ubuntu-latest
    environment:
      name: github
      url: ${{ steps.create-pr.outputs.url }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup rushjs
        uses: ./.github/actions/setup-rush
        with:
          install: true
      - name: Setup git
        uses: ./.github/actions/setup-git
        # TODO: migrate to use with: instead
        env:
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GPG_PRIVATE_KEY_BASE64: ${{ secrets.GPG_PRIVATE_KEY_BASE64 }}
          GPG_FINGERPRINT: ${{ secrets.GPG_FINGERPRINT }}
      - name: Update dependencies
        uses: ./.github/actions/run-rush
        with:
          command: deps
          args: --upgrade
      - name: Upgrade dependencies
        uses: ./.github/actions/run-rush
        with:
          command: update
          args: --full --purge
      - name: Build only needed libraries for git hooks
        uses: ./.github/actions/run-rush
        with:
          command: build
          args: --to @kcws/lintstaged-config
      - id: create-pr
        name: Create pull request
        uses: ./.github/actions/create-pr
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          title: Upgrade dependencies
          branch-prefix: deps
          commit: true
          commit-message: "chore(deps): upgrade all dependencies"
      - name: Cleanup git
        uses: ./.github/actions/cleanup-git
        with:
          gpg-fingerprint: ${{ secrets.GPG_FINGERPRINT }}
